### ISSUE TITLE
accountManager.requestSMSVerification() returns 402 error 

### ISSUE THREAD

**Issue by Goodest-Y** [gausma/libsignal-service-javascript#1]
Hi all,
it is still fine up to end of Jan , but within these few days 402 error thrown as :

accountManager.requestSMSVerification().then(result => {
console.log("Sent verification code.");
console.log("password generated : ".password);
console.log("result" + result);
}).catch(printError => {
console.log("Error" + printError);
});

ErrorHTTPError: The server rejected our query, please file a bug report. (original: promiseAjax: error response; code: 402)

Anyone has any clues on that ? I did write at throneless-tech git, just wanna raise up the issue here also.
Thanks

**Comment by tk79** [comment]
Hi,
I am also getting a "402 Payment Required" when calling this from nodered-contrib-signal-client. The detailed error message is:

```
Signal client error: {
	"name": "HTTPError",
	"code": 402,
	"response": "<html>\n<head>\n<meta http-equiv=\"Content-Type\" content=\"text/html;charset=utf-8\"/>\n<title>Error 402 Payment Required</title>\n</head>\n<body><h2>HTTP ERROR 402 Payment Required</h2>\n<table>\n<tr><th>URI:</th><td>/v1/accounts/voice/code/+49xxxxxxxxx</td></tr>\n<tr><th>STATUS:</th><td>402</td></tr>\n<tr><th>MESSAGE:</th><td>Payment Required</td></tr>\n<tr><th>SERVLET:</th><td>io.dropwizard.jersey.setup.JerseyServletContainer-289cf7db</td></tr>\n</table>\n\n</body>\n</html>\n"
}
```

**Comment by fanuch** [comment]
I believe this error code is the reply when Captcha is required [as per signal-cli source](https://github.com/AsamK/signal-cli/blob/master/man/signal-cli.1.adoc#register) which has implemented a `captcha` flag.

There would need to be a PR to work out in what format the Signal server requires the `captcha` token ( `{"captcha": "<token>"}` in data maybe?).

I've had a look at this source, but didn't get far.

I believe the modification would need to be in [WebAPI.js](https://github.com/gausma/libsignal-service-javascript/blob/master/src/WebAPI.js) and [AccountManager.js](https://github.com/gausma/libsignal-service-javascript/blob/master/src/AccountManager.js)

**Comment by Goodest-Y** [comment]
Hi all, I found the 402 error was defined in official java library as captcha,
you can somehow obtain from  https://signalcaptchas.org/registration/generate.html and extract the captcha from protocol siganlcaptcha:// and it can carry on the registration. 

Yet , if you implement in server side , perhaps you may work around with that

**Comment by fanuch** [comment]
You've just reiterated what I already covered.

> Yet , if you implement in server side , perhaps you may work around with that

What do you mean? This library will not pass the captcha token to the Signal servers.
Feel free to actually look at the links in my response to view the source code.

**Comment by gausma** [comment]
The library has been expanded so that captchas can be used.
See the additional discussion: https://github.com/gausma/nodered-contrib-signal-client/issues/18
... and the documentation for using captchas:
https://github.com/gausma/nodered-contrib-signal-client
